train.csv [파일] :
ID : 샘플별 고유 ID
age : 고객 나이
gender : 고객 성별
tenure : 고객이 서비스를 이용한 총 기간 (월)
frequent : 고객의 서비스 이용일
payment_interval : 고객의 결제 지연일
subscription_type : 고객의 서비스 등급
contract_length : 고객의 서비스 계약 기간
after_interaction : 고객이 최근 서비스 이용으로부터 경과한 기간 (일)
support_needs : 고객의 지원 필요도 (0 : 낮음 , 1 : 중간 , 2 : 높음)


test.csv [파일] :
ID : 샘플별 고유 ID
age : 고객 나이
gender : 고객 성별
tenure : 고객이 서비스를 이용한 총 기간 (월)
frequent : 고객의 서비스 이용일
payment_interval : 고객의 결제 지연일
subscription_type : 고객의 서비스 등급
contract_length : 고객의 서비스 계약 기간
after_interaction : 고객이 최근 서비스 이용으로부터 경과한 기간 (일)

In [1]:
import pandas as pd
import numpy as np

In [8]:
df = pd.read_csv('dacon/train.csv')
test = pd.read_csv('dacon/test.csv')
print(df.shape, test.shape)
df.head()

(30858, 10) (13225, 9)

,ID,age,gender,tenure,frequent,payment_interval,subscription_type,contract_length,after_interaction,support_needs
0,TRAIN_00000,54.0,F,47.0,22.0,8.0,member,90,25.0,0
1,TRAIN_00001,30.0,M,16.0,15.0,5.0,vip,360,23.0,0
2,TRAIN_00002,29.0,M,8.0,30.0,21.0,plus,30,21.0,0
3,TRAIN_00003,38.0,F,38.0,23.0,10.0,vip,90,6.0,0
4,TRAIN_00004,25.0,F,52.0,3.0,17.0,member,30,1.0,2

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30858 entries, 0 to 30857
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   ID                 30858 non-null  object
 1   age                30858 non-null  float64
 2   gender             30858 non-null  object
 3   tenure             30858 non-null  float64
 4   frequent           30858 non-null  float64
 5   payment_interval   30858 non-null  float64
 6   subscription_type  30858 non-null  object
 7   contract_length    30858 non-null  int64
 8   after_interaction  30858 non-null  float64
 9   support_needs      30858 non-null  int64
dtypes: float64(5), int64(2), object(3)
memory usage: 2.4+ MB

In [6]:
df.isna().sum()

ID                   0
age                  0
gender               0
tenure               0
frequent             0
payment_interval     0
subscription_type    0
contract_length      0
after_interaction    0
support_needs        0
dtype: int64

In [7]:
# 빈데이터가 없음

In [9]:
df.describe()

,age,tenure,frequent,payment_interval,contract_length,after_interaction,support_needs
count,30858.000000,30858.000000,30858.000000,30858.000000,30858.000000,30858.000000,30858.000000
mean,39.428479,31.250275,15.803876,12.947145,186.643010,14.546147,0.804492
std,12.423977,17.403133,8.612354,8.302702,143.948206,8.599893,0.832419
min,18.000000,1.000000,1.000000,0.000000,30.000000,1.000000,0.000000
25%,29.000000,16.000000,9.000000,6.000000,90.000000,7.000000,0.000000
50%,39.000000,32.000000,16.000000,12.000000,90.000000,14.000000,1.000000
75%,48.000000,46.000000,23.000000,19.000000,360.000000,22.000000,2.000000
max,65.000000,60.000000,30.000000,30.000000,360.000000,30.000000,2.000000

In [10]:
# 안쓰는 컬럼 삭제
df.drop('ID', axis=1, inplace=True)
test.drop('ID', axis=1, inplace=True)

In [ ]:
# 여성은 0 남성은 1로 설정
df['gender'] = df.gender.apply(lambda x: 0 if x == 'F' else 1)
df.head()

,age,gender,tenure,frequent,payment_interval,subscription_type,contract_length,after_interaction,support_needs
0,54.0,0,47.0,22.0,8.0,member,90,25.0,0
1,30.0,1,16.0,15.0,5.0,vip,360,23.0,0
2,29.0,1,8.0,30.0,21.0,plus,30,21.0,0
3,38.0,0,38.0,23.0,10.0,vip,90,6.0,0
4,25.0,0,52.0,3.0,17.0,member,30,1.0,2

In [13]:
test['gender'] = test.gender.apply(lambda x: 0 if x == 'F' else 1)
test.head()

,age,gender,tenure,frequent,payment_interval,subscription_type,contract_length,after_interaction
0,18.0,1,40.0,6.0,15.0,member,30,18.0
1,40.0,1,41.0,23.0,0.0,member,90,16.0
2,59.0,0,30.0,1.0,21.0,member,360,25.0
3,38.0,1,2.0,10.0,0.0,member,30,18.0
4,30.0,1,28.0,21.0,20.0,member,360,28.0

In [ ]:
df.subscription_type.unique(), test.subscription_type.unique() # 동일한 구독형 타입

(array(['member', 'vip', 'plus'], dtype=object),
 array(['member', 'plus', 'vip'], dtype=object))

In [ ]:
# 원핫인코딩
df_type = pd.get_dummies(df.subscription_type, dtype=int)
test_type = pd.get_dummies(test.subscription_type, dtype=int)
df_type.head()

   member  plus  vip
0       1     0    0
1       0     0    1
2       0     1    0
3       0     0    1
4       1     0    0

In [65]:
test_type.head()

   member  plus  vip
0       1     0    0
1       1     0    0
2       1     0    0
3       1     0    0
4       1     0    0

In [66]:
df2 = pd.concat([df, df_type], axis=1) # 원핫인코딩된 컬럼 병합
test2 = pd.concat([test, test_type], axis=1)
df2.head()

,age,gender,tenure,frequent,payment_interval,subscription_type,contract_length,after_interaction,support_needs,member,plus,vip
0,54.0,0,47.0,22.0,8.0,member,90,25.0,0,1,0,0
1,30.0,1,16.0,15.0,5.0,vip,360,23.0,0,0,0,1
2,29.0,1,8.0,30.0,21.0,plus,30,21.0,0,0,1,0
3,38.0,0,38.0,23.0,10.0,vip,90,6.0,0,0,0,1
4,25.0,0,52.0,3.0,17.0,member,30,1.0,2,1,0,0

In [67]:
df2.drop('subscription_type', axis=1, inplace=True)
test2.drop('subscription_type', axis=1, inplace=True)

In [68]:
abs(df2.corr()['support_needs']).sort_values() # 거의 컬럼들간의 연관성이 없어보임

plus                 0.006566
vip                  0.007390
member               0.014119
tenure               0.019409
frequent             0.021225
after_interaction    0.074641
gender               0.090690
contract_length      0.119751
payment_interval     0.153459
age                  0.168544
support_needs        1.000000
Name: support_needs, dtype: float64

In [69]:
data = df2.drop('support_needs', axis=1)
target = df2.support_needs
data.shape, target.shape

((30858, 10), (30858,))

In [37]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(data, target, test_size=.3, random_state=42)
X_train.shape, X_test.shape

((21600, 10), (9258, 10))

In [39]:
from sklearn.tree import DecisionTreeClassifier
dt = DecisionTreeClassifier(random_state=42)
dt.fit(X_train, y_train)

DecisionTreeClassifier(random_state=42)

In [40]:
dt.score(X_train, y_train)

0.9999537037037037

In [41]:
dt.score(X_test, y_test)

0.42773817239144524

In [43]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier()
knn.fit(X_train, y_train)
knn.score(X_train, y_train)

0.6248148148148148

In [44]:
knn.score(X_test, y_test)

0.4643551523007129

In [46]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(random_state=42)
rf.fit(X_train, y_train)
rf.score(X_train, y_train)

0.9999537037037037

In [47]:
rf.score(X_test, y_test)

0.5131777921797365

In [ ]:
from sklearn.svm import SVC
svm = SVC(random_state=42)
svm.fit(X_train, y_train)
svm.score(X_train, y_train)

0.4975925925925926

In [49]:
svm.score(X_test, y_test)

0.4987038237200259

In [57]:
submission = pd.read_csv('dacon/sample_submission.csv')
submission.head()

           ID  support_needs
0  TEST_00000              0
1  TEST_00001              0
2  TEST_00002              0
3  TEST_00003              0
4  TEST_00004              0

In [71]:
test2

,age,gender,tenure,frequent,payment_interval,contract_length,after_interaction,member,plus,vip
0,18.0,1,40.0,6.0,15.0,30,18.0,1,0,0
1,40.0,1,41.0,23.0,0.0,90,16.0,1,0,0
2,59.0,0,30.0,1.0,21.0,360,25.0,1,0,0
3,38.0,1,2.0,10.0,0.0,30,18.0,1,0,0
4,30.0,1,28.0,21.0,20.0,360,28.0,1,0,0
...,...,...,...,...,...,...,...,...,...,...
13220,50.0,1,32.0,13.0,11.0,360,3.0,1,0,0
13221,43.0,0,10.0,26.0,9.0,30,24.0,1,0,0
13222,61.0,1,32.0,11.0,0.0,90,10.0,0,1,0
13223,47.0,0,4.0,13.0,0.0,90,3.0,0,1,0
13224,29.0,1,9.0,10.0,9.0,360,11.0,0,1,0

In [77]:
res = rf.predict(test2)

In [79]:
res[:5]

array([2, 0, 2, 2, 0])

In [83]:
from xgboost import XGBClassifier
xgb = XGBClassifier()
xgb.fit(X_train, y_train)
xgb.score(X_train, y_train)

0.7535648148148149

In [84]:
xgb.score(X_test, y_test)

0.5022683084899546

In [95]:
from lightgbm import LGBMClassifier
lgbm = LGBMClassifier(random_state=42)
lgbm.fit(X_train, y_train)
x_res = lgbm.predict(X_train)
sum(x_res == y_train)/len(y_train)

0.609537037037037

In [96]:
res = lgbm.predict(test2)
res.shape, res[:5]

((13225,), array([2, 1, 2, 2, 0]))

In [86]:
res = xgb.predict(test2)
res[:5]

array([2, 1, 2, 2, 0])

In [97]:
submission['support_needs'] = res
submission

               ID  support_needs
0      TEST_00000              2
1      TEST_00001              1
2      TEST_00002              2
3      TEST_00003              2
4      TEST_00004              0
...           ...            ...
13220  TEST_13220              1
13221  TEST_13221              2
13222  TEST_13222              2
13223  TEST_13223              0
13224  TEST_13224              0

[13225 rows x 2 columns]

In [98]:
# submission.to_csv('test_xg.csv', index=False)
submission.to_csv('test_lgbm.csv', index=False)

In [ ]:
# 결과
# 0.4334890272 # lgbm
# 0.4440965382 # xgboost
# 0.4393394808 # 랜덤 포레스트

In [ ]:
# 테스트용 - 완료 후 삭제
from sklearn.metrics import f1_score

pub = pd.read_csv('public.csv')
pri = pd.read_csv('private.csv')

pub_score = submission[submission['ID'].isin(pub['ID'])]
pri_score = submission[submission['ID'].isin(pri['ID'])]

print(f1_score(pub['support_needs'], pub_score['support_needs'], average='macro'))
print(f1_score(pri['support_needs'], pri_score['support_needs'], average='macro'))