# 1. 회귀 문제

1. 캘리포니아 주택 가격 데이터셋 : scikit 의 fetch_california_housing()
2. 캘리포니아 지역의 인구, 중간 소득, 주택 연식 등의 특성을 이용해 주택의 중간 가격을 예측하는 회귀 문제입니다. 
3. LinearRegressor, SVM, KNN 로 학습하고 이미지 캡쳐로 업로드
    - "정규화" 처리 한 것과
    - MSE, MAE, RMSE, R2 평가지표 출력 포함
4. 다음 같이 탑재 한다.

In [ ]:
import ssl # 위 에러에 대한 대처법
from sklearn.datasets import fetch_california_housing
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error, root_mean_squared_error
import pandas as pd
import numpy as np

ssl._create_default_https_context = ssl._create_unverified_context
california_housing = fetch_california_housing(as_frame=True) # as_frame=True loads as a pandas DataFrame

In [6]:
df = pd.DataFrame(california_housing.data, columns=california_housing.feature_names)
print(df.shape)
df.head()

(20640, 8)

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25

In [10]:
print(california_housing.target_names)
print(california_housing.target[:5])

['MedHouseVal']
0    4.526
1    3.585
2    3.521
3    3.413
4    3.422
Name: MedHouseVal, dtype: float64

In [12]:
std = StandardScaler()
# lin = LinearRegression()
knn = KNeighborsClassifier()
svm = SVC()

# 2. 분류문제

    수업중 진행한 “07지도학습KNN”, “07지도학습SVM” 에서 사용한 scikit 의 load_wine, load_breast_cancer 데이터를 DecisionTree 로 분류하고 평가지표 정확도, classification_report 출력

In [ ]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.datasets import load_wine, load_breast_cancer
from sklearn.preprocessing import StandardScaler, MinMaxScaler, LabelEncoder
from sklearn.metrics import classification_report
from sklearn.model_selection import train_test_split
import pandas as pd
import numpy as np
wine, cancer = load_wine(), load_breast_cancer()
df_wine = pd.DataFrame(wine.data, columns=wine.feature_names)
df_cancer = pd.DataFrame(cancer.data, columns=cancer.feature_names)
df_wine.head()

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280/od315_of_diluted_wines,proline
0,14.23,1.71,2.43,15.6,127.0,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065.0
1,13.20,1.78,2.14,11.2,100.0,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050.0
2,13.16,2.36,2.67,18.6,101.0,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185.0
3,14.37,1.95,2.50,16.8,113.0,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480.0
4,13.24,2.59,2.87,21.0,118.0,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735.0

In [3]:
# wine.target_names, wine.target
# cancer.target_names, cancer.target

In [4]:
# df_wine.head()
# df_cancer.head()

In [5]:
c_X_train, c_X_test, c_y_train, c_y_test = train_test_split(df_cancer, cancer.target, test_size=.3, random_state=42)
w_X_train, w_X_test, w_y_train, w_y_test = train_test_split(df_wine, wine.target, test_size=.3, random_state=42)
print(c_X_train.shape, c_y_train.shape)
print(w_X_train.shape, w_y_train.shape)

(398, 30) (398,)
(124, 13) (124,)

In [6]:
dt_cancer = DecisionTreeClassifier()
dt_wine = DecisionTreeClassifier()

In [7]:
%%time
dt_cancer.fit(c_X_train, c_y_train)
dt_wine.fit(w_X_train, w_y_train)

CPU times: total: 15.6 ms
Wall time: 14.7 ms

DecisionTreeClassifier()

In [8]:
wine_pred = dt_wine.predict(w_X_train)
print(dt_wine.score(w_X_train, w_y_train))
print(classification_report(w_y_train, wine_pred))

1.0
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        40
           1       1.00      1.00      1.00        50
           2       1.00      1.00      1.00        34

    accuracy                           1.00       124
   macro avg       1.00      1.00      1.00       124
weighted avg       1.00      1.00      1.00       124

In [9]:
wine_pred = dt_wine.predict(w_X_test)
print(dt_wine.score(w_X_test, w_y_test))
print(classification_report(w_y_test, wine_pred))

0.9629629629629629
              precision    recall  f1-score   support

           0       1.00      0.95      0.97        19
           1       0.91      1.00      0.95        21
           2       1.00      0.93      0.96        14

    accuracy                           0.96        54
   macro avg       0.97      0.96      0.96        54
weighted avg       0.97      0.96      0.96        54

In [10]:
cancer_pred = dt_cancer.predict(c_X_train)
print(dt_cancer.score(c_X_train, c_y_train))
print(classification_report(c_y_train, cancer_pred))

1.0
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       149
           1       1.00      1.00      1.00       249

    accuracy                           1.00       398
   macro avg       1.00      1.00      1.00       398
weighted avg       1.00      1.00      1.00       398

In [11]:
cancer_pred = dt_cancer.predict(c_X_test)
print(dt_cancer.score(c_X_test, c_y_test))
print(classification_report(c_y_test, cancer_pred))

0.9239766081871345
              precision    recall  f1-score   support

           0       0.87      0.94      0.90        63
           1       0.96      0.92      0.94       108

    accuracy                           0.92       171
   macro avg       0.91      0.93      0.92       171
weighted avg       0.93      0.92      0.92       171